services:

  postgres:

    build:
      context: .
      dockerfile: docker/postgres/Dockerfile

    container_name: ${POSTGRES_CONTAINER}

    image: retaillake/postgres:1.0.0

    restart: unless-stopped

    env_file:
      - .env

    environment:

      POSTGRES_DB: ${POSTGRES_DB}

      POSTGRES_USER: ${POSTGRES_USER}

      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:

      - "${POSTGRES_PORT}:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:

      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER}"
        ]

      interval: 10s

      timeout: 5s

      retries: 5

      start_period: 10s

    networks:

      - retaillake-network


  spark:

    build:

      context: .

      dockerfile: docker/spark/Dockerfile

    image: retaillake/spark:1.0.0

    container_name: retail-spark

    restart: unless-stopped

    depends_on:

      postgres:

        condition: service_healthy

    volumes:

      - ./src:/app/src
      - ./duckdb:/app/duckdb
      - ./logs:/app/logs
      - ./data:/app/data
      - ./docker/spark/conf/log4j2.properties:/opt/spark/conf/log4j2.properties

    networks:

      - retaillake-network

    environment:
      PYTHONPATH: /app/src

  airflow:
    image: retaillake/airflow:1.0.0

    build:
      context: .
      dockerfile: docker/airflow/Dockerfile

    container_name: retail-airflow

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:

      AIRFLOW__CORE__EXECUTOR: LocalExecutor
#

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

        # ----------------------------
        # Development Optimizations
        # ----------------------------

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60

      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 60

      AIRFLOW__SCHEDULER__PARSING_PROCESSES: 1

      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "False"

      AIRFLOW_UID: 50000

    ports:

      - "8080:8080"

    volumes:

      - ./airflow/dags:/opt/airflow/dags

      - ./airflow/logs:/opt/airflow/logs

      - ./airflow/plugins:/opt/airflow/plugins

    command: standalone

    networks:

      - retaillake-network

volumes:

  postgres_data:

networks:

  retaillake-network:

    driver: bridge





