status = error
name = SparkLogConfig

rootLogger.level = warn

rootLogger.appenderRefs = console

rootLogger.appenderRef.console.ref = Console

appender.console.type = Console

appender.console.name = Console

appender.console.target = SYSTEM_ERR

appender.console.layout.type = PatternLayout

appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c - %m%n

logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = error

logger.parquet.name = org.apache.parquet
logger.parquet.level = error

logger.hive.name = org.apache.hadoop.hive
logger.hive.level = error

logger.netty.name = io.netty
logger.netty.level = error